spring.application.name=AMS

## DB Configuration
#spring.datasource.url=${DATASOURCE_URL}
#spring.datasource.username=${DATASOURCE_USERNAME}
#spring.datasource.password=${DATASOURCE_PASSWORD}

## Prod DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ams
spring.datasource.username=ankita
spring.datasource.password=COGNIVAA@postgres12


## Local DB Configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/ams
#spring.datasource.username=postgres
#spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Optional logging
debug=true

# Hikari pool settings
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.connection-timeout=30000

# server.address=127.0.0.1
server.port=8088
